[package]
name = "env-yoink"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
grep = "0.2.11"
regex = "1.7.3"
walkdir = "2.3.3"
